// This is generated by writeCoreEval; please edit!
/* eslint-disable */

const manifestBundleRef = {bundleID:"b1-dfba4c34c9ceaac961c837faa533a41bb940bf2bd1824d0b8a68d4037595d6777fb10469925f7a7b91e23ea1c6f18dd40c7ddf42d9c51d3e1c135f609cda7d22"};
const getManifestCall = harden([
  "getManifest",
  {
    installationRef: {
      bundleID: "b1-609053267b7d4c0be420d94e01472e441fd40c8cd7fcec088fc19edf0eb12ccac83e6474884179247cf0e4a1a9057b62d13a41ac406b251ed3b978801aa6f598",
    },
    options: {
      assetInfo: [
        [
          "uist",
          {
            baseDenom: "uist",
            baseName: "agoric",
            chainName: "agoric",
          },
        ],
        [
          "ibc/94EB1E9A676004E74ECF47F8E4BF183F4017CE0630A4D1AC7C7D9EB9CD6A3D53",
          {
            baseDenom: "uausdc",
            baseName: "osmosis",
            brandKey: "AUSDC",
            chainName: "agoric",
          },
        ],
        [
          "ibc/3C870A71004EAD01A29709B779FECBB9F150559B1276825584E149596BD450DE",
          {
            baseDenom: "wavax-wei",
            baseName: "osmosis",
            brandKey: "WAVAX",
            chainName: "agoric",
          },
        ],
      ],
      chainInfo: {
        agoric: {
          chainId: "agoriclocal",
          connections: {
            "osmo-test-5": {
              client_id: "07-tendermint-0",
              counterparty: {
                client_id: "07-tendermint-4430",
                connection_id: "connection-3871",
              },
              id: "connection-0",
              state: 3,
              transferChannel: {
                channelId: "channel-0",
                counterPartyChannelId: "channel-10158",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          stakingTokens: [
            {
              denom: "ubld",
            },
          ],
        },
        osmosis: {
          chainId: "osmo-test-5",
          connections: {
            agoriclocal: {
              client_id: "07-tendermint-4430",
              counterparty: {
                client_id: "07-tendermint-0",
                connection_id: "connection-0",
              },
              id: "connection-3871",
              state: 3,
              transferChannel: {
                channelId: "channel-10158",
                counterPartyChannelId: "channel-0",
                counterPartyPortId: "transfer",
                ordering: 0,
                portId: "transfer",
                state: 3,
                version: "ics20-1",
              },
            },
          },
          stakingTokens: [
            {
              denom: "uosmo",
            },
          ],
        },
      },
    },
  },
]);
const customManifest = {
  startAxelarGmp: {
    consume: {
      agoricNames: true,
      board: true,
      chainStorage: true,
      chainTimerService: true,
      cosmosInterchainService: true,
      localchain: true,
      startUpgradable: true,
    },
    installation: {
      consume: {
        axelarGmp: true,
      },
    },
    instance: {
      produce: {
        axelarGmp: true,
      },
    },
    issuer: {
      consume: {
        BLD: true,
        IST: true,
      },
    },
  },
};

// Make a behavior function and "export" it by way of script completion value.
// It is constructed by an anonymous invocation to ensure the absence of a global binding
// for makeCoreProposalBehavior, which may not be necessary but preserves behavior pre-dating
// https://github.com/Agoric/agoric-sdk/pull/8712 .
const behavior = (({
  manifestBundleRef,
  getManifestCall: [manifestGetterName, ...manifestGetterArgs],
  customManifest,
  E,
  log = console.info,
  customRestoreRef,
}) => {
  const { entries, fromEntries } = Object;

  /**
   * Given an object whose properties may be promise-valued, return a promise
   * for an analogous object in which each such value has been replaced with its
   * fulfillment.
   * This is a non-recursive form of endo `deeplyFulfilled`.
   *
   * @template T
   * @param {{[K in keyof T]: (T[K] | Promise<T[K]>)}} obj
   * @returns {Promise<T>}
   */
  const shallowlyFulfilled = async obj => {
    if (!obj) {
      return obj;
    }
    const awaitedEntries = await Promise.all(
      entries(obj).map(async ([key, valueP]) => {
        const value = await valueP;
        return [key, value];
      }),
    );
    return fromEntries(awaitedEntries);
  };

  const makeRestoreRef = (vatAdminSvc, zoe) => {
    /** @type {(ref: import\('./externalTypes.js').ManifestBundleRef) => Promise<Installation<unknown>>} */
    const defaultRestoreRef = async bundleRef => {
      // extract-proposal.js creates these records, and bundleName is
      // the optional name under which the bundle was installed into
      // config.bundles
      const bundleIdP =
        'bundleName' in bundleRef
          ? E(vatAdminSvc).getBundleIDByName(bundleRef.bundleName)
          : bundleRef.bundleID;
      const bundleID = await bundleIdP;
      const label = bundleID.slice(0, 8);
      return E(zoe).installBundleID(bundleID, label);
    };
    return defaultRestoreRef;
  };

  /** @param {ChainBootstrapSpace & BootstrapPowers & { evaluateBundleCap: any }} powers */
  const coreProposalBehavior = async powers => {
    // NOTE: `powers` is expected to match or be a superset of the above `permits` export,
    // which should therefore be kept in sync with this deconstruction code.
    // HOWEVER, do note that this function is invoked with at least the *union* of powers
    // required by individual moduleBehaviors declared by the manifest getter, which is
    // necessary so it can use `runModuleBehaviors` to provide the appropriate subset to
    // each one (see ./writeCoreEvalParts.js).
    // Handle `powers` with the requisite care.
    const {
      consume: { vatAdminSvc, zoe, agoricNamesAdmin },
      evaluateBundleCap,
      installation: { produce: produceInstallations },
      modules: {
        utils: { runModuleBehaviors },
      },
    } = powers;

    // Get the on-chain installation containing the manifest and behaviors.
    log('evaluateBundleCap', {
      manifestBundleRef,
      manifestGetterName,
      vatAdminSvc,
    });
    let bcapP;
    if ('bundleName' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getNamedBundleCap(manifestBundleRef.bundleName);
    } else if ('bundleID' in manifestBundleRef) {
      bcapP = E(vatAdminSvc).getBundleCap(manifestBundleRef.bundleID);
    } else {
      const keys = Reflect.ownKeys(manifestBundleRef).map(key =>
        typeof key === 'string' ? JSON.stringify(key) : String(key),
      );
      const keysStr = `[${keys.join(', ')}]`;
      throw Error(
        `bundleRef must have own bundleName or bundleID, missing in ${keysStr}`,
      );
    }
    const bundleCap = await bcapP;

    const proposalNS = await evaluateBundleCap(bundleCap);

    // Get the manifest and its metadata.
    log('execute', {
      manifestGetterName,
      bundleExports: Object.keys(proposalNS),
    });
    const restoreRef = customRestoreRef || makeRestoreRef(vatAdminSvc, zoe);
    const {
      manifest,
      options: rawOptions,
      installations: rawInstallations,
    } = await proposalNS[manifestGetterName](
      harden({ restoreRef }),
      ...manifestGetterArgs,
    );

    // Await promises in the returned options and installations records.
    const [options, installations] = await Promise.all(
      [rawOptions, rawInstallations].map(shallowlyFulfilled),
    );

    // Publish the installations for our dependencies.
    const installationEntries = entries(installations || {});
    if (installationEntries.length > 0) {
      const installAdmin = E(agoricNamesAdmin).lookupAdmin('installation');
      await Promise.all(
        installationEntries.map(([key, value]) => {
          produceInstallations[key].reset();
          produceInstallations[key].resolve(value);
          return E(installAdmin).update(key, value);
        }),
      );
    }

    // Evaluate the manifest.
    return runModuleBehaviors({
      // Remember that `powers` may be arbitrarily broad.
      allPowers: powers,
      behaviors: proposalNS,
      manifest: customManifest || manifest,
      makeConfig: (name, _permit) => {
        log('coreProposal:', name);
        return { options };
      },
    });
  };

  return coreProposalBehavior;
})({ manifestBundleRef, getManifestCall, customManifest, E });
behavior;
